
# The number of experimental groups, world 0 is always control
num_worlds: 8

# Which information to display to users in experimental group
# Options: True, False
show_views: True
show_downloads: True
show_ratings: True

# How to determine the order artifacts are displayed in
# Options: view_count, download_count, mean_rating, random
sort_by: view_count

# The title to display on the gallery page
title: Comic Gallery

# List of artifacts to display on the gallery page
artifacts:
    - label: XKCD
      url: https://imgs.xkcd.com/comics/here_to_help_2x.png
    - label: The Adventures of Business Cat
      url: http://www.businesscat.happyjar.com/wp-content/uploads/2014/01/2014-01-07-Coffee.png
      view_count: 1337
      download_count: 237
      rating_count: 0
      start_rating: 2.5
    - label: Saturday Morning Breakfast Cereal
      url: http://www.smbc-comics.com/comics/20090719.gif
      download_count: 240
    - label: Questionable Content
      url: http://www.questionablecontent.net/comics/3586.png
      download_count: 230

