
# The number of experimental groups, world 0 is always control
num_worlds: 3

# The number of columns to display
# Options: 1, 2, 3, 4
num_columns: 2

# Which information to display to users in experimental group
# Options: True, False
show_views: True
show_downloads: True
show_ratings: True

# How to determine the order artifacts are displayed in
# Options: view_count, download_count, mean_rating, random
sort_by: mean_rating

# The title to display on the gallery page
title: Comic Gallery

# List of artifacts to display on the gallery page
artifacts:
    # Each artifact must have at least a label and a url
    - label: War and Peas
      url: https://linsedition.files.wordpress.com/2017/11/war-and-peas-good-girl.jpg
      # Initial counts and ratings can be specified as an array with one entry for each world
      # or as a single number used by all worlds
      view_count:
        - 100
        - 200
        - 300
      download_count: 10
      rating_count: 1
      rating: 5
    - label: That Comic Thing
      url: https://i.redd.it/bbbb51isscwz.jpg
    - label: Sinewyn
      url: https://i.imgur.com/lucke0K.png
    - label: 4AM Shower
      url: https://i.redd.it/n6m1ys4f9awz.jpg
    - label: Against Stupidity
      url: https://againststupiditycomic.files.wordpress.com/2017/11/6.png
    - label: Knot
      url: https://i.redditmedia.com/JofrUdHpKN_HNqJgwU57u3IryNHo8kuI2i14_hqUJu0.jpg?w=543&s=c3f4f1cd217ef7fb3bd920539fc31d4c
    - label: Drawings of Dogs
      url: https://i.imgur.com/gFfU4hP.jpg
    - label: It Fools a Monster
      url: https://i.redd.it/ab7x93n50dwz.jpg
    - label: Gone Into Rapture
      url: https://i.imgur.com/QxJQXep.png
    - label: Poorly Adjusted
      url: https://i.redd.it/h3p32be62dwz.jpg
    - label: Charmy's Army
      url: https://charmysarmy.files.wordpress.com/2017/11/11nov2017_charmy-week-45-1105-1011-color-stacked-web.jpg?w=750
    - label: Don't Be Dad
      url: https://i.redditmedia.com/nxGGuCii-WawI_WXGTqq1m-0s72auE0Drhw8RymoXmc.png?w=768&s=ed0c54fdbf9c21786f77a1b651f64c80

